all: compile run clean

compile: 

	@echo "-------------------------------------------"
	@echo "Compiling..."
	@javac *.java 

run:
	@echo "-------------------------------------------"
	@echo "Running the tests...."
	
	@echo "==========================================="
	@java TestCode
	@echo "==========================================="

clean:
	@echo "-------------------------------------------"
	@echo "Cleaning..."
	@rm -f *.class
