# Makefile for compiling and running 210104004093_Kibar_Emre.lisp with SBCL

# The name of the Lisp file
LISP_FILE = 210104004093_Kibar_Emre.lisp

# The name of the executable (SBCL)
EXECUTABLE = sbcl

# Default target: compile and run the Lisp file
all: run

# Run the Lisp file using SBCL
run:
	$(EXECUTABLE) --load $(LISP_FILE) --quit

# Phony targets (not actual files)
.PHONY: all run
